"""
Convenience wrapper around the autogenerated Jellyfin OpenAPI client.

The generated client lives in :mod:`jellyfin_apiclient_python.openapi._generated`.
This module provides a thin :class:`Jellyfin` wrapper that handles authentication
and exposes all generated endpoints dynamically under :attr:`Jellyfin.api`:

    jf.api.<group>.<endpoint>

Endpoint proxies are callable (defaulting to ``sync_detailed``) and will
auto-inject ``client=jf.client`` when omitted.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Dict, Callable
import functools
import importlib
import inspect
import pkgutil
import sys
import textwrap
import uuid

if sys.version_info < (3, 10):
    from jellyfin_apiclient_python.openapi.compat import install_legacy_openapi_compat

    install_legacy_openapi_compat()

# --- Generated imports (no jellyfin_openapi name) ---
from ._generated.client import Client as UnauthClient  # noqa: E402
from ._generated.client import AuthenticatedClient  # noqa: E402

_DEFAULT = object()  # sentinel


def _codeblock(s: str) -> str:
    """Dedent + strip docstrings so help() output is clean."""
    return textwrap.dedent(s).strip()


def _default_emby_authorization(
    *,
    client_name: str,
    device: str,
    device_id: str,
    version: str,
) -> str:
    # Jellyfin expects this exact style for client identification.
    return (
        f'MediaBrowser Client="{client_name}", '
        f'Device="{device}", DeviceId="{device_id}", '
        f'Version="{version}"'
    )


@dataclass(frozen=True)
class JellyfinAuth:
    access_token: str
    user_id: str


class Jellyfin:
    """
    Dynamic facade over the generated OpenAPI client.

    This provides the following conviniences over using the raw generated
    openapi client:

     - Handles authentication with username / password
     - Put all generated endpoints under `.api.*`
     - Auto-injects ``client`` into generated calls when possible

    Design goals:
      - Keep manual surface small: login + client/auth properties
      - Avoid hardcoding endpoint wrappers; instead discover dynamically

    Usage:
        jf = Jellyfin(base_url=..., username=..., password=...)
        jf.login()
        resp = jf.api.library.get_media_folders()
    """
    DEFAULTS: Dict[str, Any] = {
        "client_name": "openapi-python-client",
        "device": "python",
        "device_id": "python-jellyfin",
        "version": "0.1.0",
        "timeout": 30.0,
        "mount_api": True,
        # Auth header defaults:
        "auth_header_name": "X-Emby-Token",
        "auth_prefix": "",
    }

    def __init__(
        self,
        *,
        base_url: str,
        username: Optional[str] = None,
        password: Optional[str] = None,
        client_name: Any = _DEFAULT,
        device: Any = _DEFAULT,
        device_id: Any = _DEFAULT,
        version: Any = _DEFAULT,
        timeout: Any = _DEFAULT,
        mount_api: Any = _DEFAULT,
        auth_header_name: Any = _DEFAULT,
        auth_prefix: Any = _DEFAULT,
        extra_headers: Optional[Dict[str, str]] = None,
    ):
        # Resolve defaults at runtime (no class-variable default trap)
        DEFAULTS = self.DEFAULTS
        client_name = DEFAULTS["client_name"] if client_name is _DEFAULT else client_name
        device = DEFAULTS["device"] if device is _DEFAULT else device
        device_id = DEFAULTS["device_id"] if device_id is _DEFAULT else device_id
        version = DEFAULTS["version"] if version is _DEFAULT else version
        timeout = DEFAULTS["timeout"] if timeout is _DEFAULT else timeout
        mount_api = DEFAULTS["mount_api"] if mount_api is _DEFAULT else mount_api
        auth_header_name = DEFAULTS["auth_header_name"] if auth_header_name is _DEFAULT else auth_header_name
        auth_prefix = DEFAULTS["auth_prefix"] if auth_prefix is _DEFAULT else auth_prefix

        self.base_url = base_url.rstrip("/")

        self._timeout = float(timeout)

        self._auth_header_name = str(auth_header_name)
        self._auth_prefix = str(auth_prefix)

        # Jellyfin requires the identity header for lots of endpoints.
        self._identity_headers: Dict[str, str] = {
            "X-Emby-Authorization": _default_emby_authorization(
                client_name=str(client_name),
                device=str(device),
                device_id=str(device_id),
                version=str(version),
            )
        }
        if extra_headers:
            self._identity_headers.update(extra_headers)

        # Underlying generated clients
        self._unauth = UnauthClient(
            base_url=self.base_url,
            headers=self._identity_headers,
            timeout=self._timeout,
        )
        self._authed: Optional[AuthenticatedClient] = None

        # Optional stored credentials for username / password login
        self._username: str | None = username
        self._password: str | None = password
        self._user_id: uuid.UUID | None = None

        self.api = ApiNamespace(
            "api",
            doc=_codeblock(
                """
                Jellyfin API namespace (dynamically generated).

                This namespace contains endpoint groups created by crawling the generated
                OpenAPI client under ./_generated/api/*`.

                Usage
                -----
                jf.api.<group>.<endpoint>.sync(...)
                jf.api.<group>.<endpoint>.sync_detailed(...)
                jf.api.<group>.<endpoint>.asyncio(...)
                jf.api.<group>.<endpoint>.asyncio_detailed(...)

                Convenience behavior
                --------------------
                Endpoint proxies will auto-inject `client=jf.client` if you do not provide it.

                Introspection
                -------------
                dir(jf.api)                  -> list groups
                dir(jf.api.items)            -> list endpoints in the "items" group
                help(jf.api.items)           -> show info about an endpoint group
                help(jf.api.items.get_items) -> show info about a specific endpoint
                help(jf.api.items.get_items.asyncio_detailed) -> show info about the explicit endpoint wrapper
                """
            ),

        )
        if mount_api:
            self._mount_generated_api()

    # -------------------------
    # Credentials / Client access
    # -------------------------

    @property
    def token(self) -> str:
        if not self._authed:
            raise RuntimeError("Not authenticated; call login() or login_with_token().")
        return self._authed.token

    @property
    def user_id(self) -> uuid.UUID:
        if not self._user_id:
            self._populate_user_info()
        return self._user_id

    @property
    def username(self) -> str:
        if not self._username:
            self._populate_user_info()
        return self._username

    def _populate_user_info(self):
        resp = self.api.user.get_current_user.sync_detailed()
        self._user_id = resp.parsed.id
        self._username = resp.parsed.name

    @property
    def client(self) -> AuthenticatedClient:
        if not self._authed:
            raise RuntimeError("Not logged in. Call jf.login() first.")
        return self._authed

    def login(self, *, username: str | None = None, password: str | None = None) -> "Jellyfin":
        """
        Login using username/password and configure this instance with the returned token.

        If `password` is provided here, it is used only for this call and is not stored.
        If not provided, the instance password (if any) is used.

        Returns:
            self (for chaining)
        """
        username = username if username is not None else self._username
        if not username:
            raise RuntimeError("No username provided. Pass username=... to the constructor or login().")

        pw = password if password is not None else self._password
        if pw is None:
            raise RuntimeError(
                "No password available. Pass password=... to login() for an ephemeral login, "
                "or set password=... on the constructor to remember it."
            )

        from ._generated.api.user import authenticate_user_by_name
        from ._generated.models import AuthenticateUserByName

        body = AuthenticateUserByName(username=username, pw=pw)
        resp = authenticate_user_by_name.sync_detailed(client=self._unauth, body=body)

        if resp.status_code != 200 or resp.parsed is None:
            msg = resp.content.decode("utf-8", "ignore") if resp.content else ""
            raise RuntimeError(f"Login failed ({resp.status_code}): {msg}")

        parsed = resp.parsed
        token = getattr(parsed, "access_token", None)
        user = getattr(parsed, "user", None)
        user_id = getattr(user, "id", None)

        if not token:
            raise RuntimeError("Login response missing access token")
        if not user_id:
            raise AssertionError("Login response missing user id. This should not happen")

        self._user_id = user_id
        self._username = user.name

        return self.login_with_token(token=token)


    def login_with_token(self, token: str) -> "Jellyfin":
        """
        Configure this instance to use an existing token (no username/password
        required).

        Returns:
            self (for chaining)
        """
        self._authed = AuthenticatedClient(
            base_url=self.base_url,
            token=token,
            prefix=self._auth_prefix,
            auth_header_name=self._auth_header_name,
            headers=self._identity_headers,
            timeout=self._timeout,
        )
        return self

    # -------------------------
    # Dynamic API mounting
    # -------------------------

    def _mount_generated_api(self) -> None:
        """
        Crawls ._generated.api.* and mounts endpoints under jf.api.<group>.<endpoint>.

        Each endpoint is wrapped in EndpointProxy so client= is auto-supplied when missing.
        """
        api_pkg_name = f"{__package__}._generated.api"
        api_pkg = importlib.import_module(api_pkg_name)

        # First-level packages under api/ become namespaces (user, library, system, etc.)
        for _, group_mod_name, group_is_pkg in pkgutil.iter_modules(api_pkg.__path__, api_pkg.__name__ + "."):
            if not group_is_pkg:
                continue

            group_mod = importlib.import_module(group_mod_name)
            group_name = group_mod_name.split(".")[-1]
            group_ns = ApiNamespace(
                group_name,
                doc=_codeblock(
                    f"""
                    Generated endpoint group: `{group_name}`

                    This namespace corresponds to modules under:

                        `_generated/api/{group_name}/`

                    Each attribute is an `EndpointProxy` wrapping a generated endpoint module.

                    Usage
                    -----
                        jf.api.{group_name}.<endpoint>.sync(...)
                        jf.api.{group_name}.<endpoint>.sync_detailed(...)

                    Introspection
                    -------------
                        dir(jf.api.{group_name}) -> list endpoints in this group
                        help(jf.api.{group_name}.<endpoint>) -> show proxy docs
                    """),
            )


            # Each .py file under that group is an endpoint module
            for _, endpoint_mod_name, endpoint_is_pkg in pkgutil.iter_modules(
                group_mod.__path__, group_mod.__name__ + "."
            ):
                if endpoint_is_pkg:
                    continue
                endpoint_mod = importlib.import_module(endpoint_mod_name)
                endpoint_name = endpoint_mod_name.split(".")[-1]

                # Wrap with proxy to auto-inject client=
                setattr(group_ns, endpoint_name, EndpointProxy(self, endpoint_mod))

            setattr(self.api, group_name, group_ns)

    def __repr__(self) -> str:
        return (
            f"<Jellyfin base_url={self.base_url!r} "
            f"user={self._username!r} authed={self._authed is not None}>"
        )



class ApiNamespace:
    """
    A simple object that holds dynamically attached endpoint proxies.
    The documentation will be overwritten for each instance.
    """
    def __init__(self, name: str, doc: str | None = None):
        self.__name__ = name
        self.__doc__ = doc or ""

    def __repr__(self) -> str:
        keys = [k for k in self.__dict__.keys() if not k.startswith("_")]
        keys.sort()
        preview = ", ".join(keys[:12]) + ("..." if len(keys) > 12 else "")
        return f"<ApiNamespace {self.__name__}: {preview}>"

    def __dir__(self) -> list[str]:
        keys = [k for k in self.__dict__.keys() if not k.startswith("_")]
        keys.sort()
        return keys

    def __getattr__(self, name: str) -> Any:
        raise AttributeError(
            f"{self.__name__!r} has no attribute {name!r}. "
            f"Try dir(jf.api.{self.__name__}) to see available endpoints."
        )



class EndpointProxy:
    """
    Wraps a generated endpoint module and provides call helpers.

    The proxy:
      - auto-populates client=... if missing
      - forwards .sync / .sync_detailed / .asyncio / .asyncio_detailed
      - is callable (defaults to .sync_detailed)
      - exposes the raw generated module via ._module
    """

    def __init__(self, owner: "Jellyfin", module: Any):
        self._owner = owner
        self._module = module

        # Common generated entrypoints
        self.sync = self._wrap("sync")
        self.sync_detailed = self._wrap("sync_detailed")
        self.asyncio = self._wrap("asyncio")
        self.asyncio_detailed = self._wrap("asyncio_detailed")

        # Make help(proxy) show a useful signature (match sync_detailed, hide client)
        generated_doc = ""
        try:
            fn = getattr(module, "sync_detailed")
            sig = inspect.signature(fn)
            params = [p for p in sig.parameters.values() if p.name != "client"]
            self.__signature__ = sig.replace(parameters=params)  # type: ignore[attr-defined]
        except Exception:
            # If sync_detailed doesn't exist or signature can't be computed, omit.
            pass
        else:
            generated_doc = fn.__doc__.strip()

        header = _codeblock(f"""
        EndpointProxy for generated endpoint module:

            {module.__name__}

        Calling this proxy is equivalent to calling ``.sync_detailed(...)``:

            jf.api.<group>.<endpoint>(...)  ==  jf.api.<group>.<endpoint>.sync_detailed(...)

        Available call variants (when present):

            - .sync(...)
            - .sync_detailed(...)
            - .asyncio(...)
            - .asyncio_detailed(...)

        Convenience behavior:

            If the underlying generated function accepts ``client=``, it will be
            auto-populated from ``jf.client`` if omitted.

        Introspection tips:

            - help(<this>.sync_detailed) -> endpoint docs + signature
            - <this>._module             -> raw generated module
            - dir(<this>)                -> list available variants
        """)

        if generated_doc:
            self.__doc__ = header + "\n\n" + _codeblock(f"""
            Generated endpoint documentation
            -------------------------------
            {generated_doc}
            """)
        else:
            self.__doc__ = header


    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        return self.sync_detailed(*args, **kwargs)

    def __repr__(self) -> str:
        return f"<EndpointProxy {self._module.__name__}>"

    def __dir__(self) -> list[str]:
        base = ["sync", "sync_detailed", "asyncio", "asyncio_detailed"]
        extra = [k for k in dir(self._module) if not k.startswith("_")]
        return sorted(set(base + extra))

    def _wrap(self, fn_name: str) -> Callable[..., Any]:
        fn = getattr(self._module, fn_name, None)
        if fn is None:
            def _missing(*args: Any, **kwargs: Any) -> Any:
                raise AttributeError(f"{self._module.__name__} has no attribute {fn_name}")
            _missing.__doc__ = _codeblock(
                f"""
                Missing generated function:

                    {self._module.__name__}.{fn_name}

                This endpoint module does not provide the requested call variant.
                Use one of the other call variants, e.g. ``sync_detailed`` or
                ``asyncio_detailed``.
                """
            )
            return _missing

        try:
            orig_sig = inspect.signature(fn)
        except (TypeError, ValueError):
            orig_sig = None

        user_sig = None
        if orig_sig is not None:
            params = [p for p in orig_sig.parameters.values() if p.name != "client"]
            user_sig = orig_sig.replace(parameters=params)

        @functools.wraps(fn)
        def _call(*args: Any, **kwargs: Any) -> Any:
            if "client" not in kwargs:
                if orig_sig is None or "client" in orig_sig.parameters:
                    kwargs["client"] = self._owner.client
            return fn(*args, **kwargs)

        if user_sig is not None:
            _call.__signature__ = user_sig  # type: ignore[attr-defined]
        elif orig_sig is not None:
            _call.__signature__ = orig_sig  # type: ignore[attr-defined]

        proxy_notes = _codeblock(f"""
        Notes
        -----
        This function is exposed through an ``EndpointProxy`` attached to the ``Jellyfin`` wrapper.

        - If you do not supply ``client=...``, it will be auto-populated from ``jf.client``.
        - You can override this by explicitly passing ``client=...``.
        - Underlying generated function: ``{self._module.__name__}.{fn_name}``
        """)

        base_doc = (fn.__doc__ or "").rstrip()
        _call.__doc__ = (base_doc + "\n\n" + proxy_notes) if base_doc else proxy_notes
        return _call

    def __getattr__(self, item: str) -> Any:
        return getattr(self._module, item)
