from enum import Enum

# from enum import StrEnum


class StrEnum(str, Enum):
    """
    Minimal string enum that works with Python 3.6+
    """
    def __str__(self):
        return self.value

    @classmethod
    def _missing_(cls, value):
        # Allow case-insensitive lookups
        for member in cls:
            if member.value.lower() == value.lower():
                return member
        return None


class ItemType(StrEnum):
    AGGREGATE_FOLDER = "AggregateFolder"
    AUDIO = "Audio"
    AUDIO_BOOK = "AudioBook"
    BASE_PLUGIN_FOLDER = "BasePluginFolder"
    BOOK = "Book"
    BOX_SET = "BoxSet"
    CHANNEL = "Channel"
    CHANNEL_FOLDER_ITEM = "ChannelFolderItem"
    COLLECTION_FOLDER = "CollectionFolder"
    EPISODE = "Episode"
    FOLDER = "Folder"
    GENRE = "Genre"
    MANUAL_PLAYLISTS_FOLDER = "ManualPlaylistsFolder"
    MOVIE = "Movie"
    LIVE_TV_CHANNEL = "LiveTvChannel"
    LIVE_TV_PROGRAM = "LiveTvProgram"
    MUSIC_ALBUM = "MusicAlbum"
    MUSIC_ARTIST = "MusicArtist"
    MUSIC_GENRE = "MusicGenre"
    MUSIC_VIDEO = "MusicVideo"
    PERSON = "Person"
    PHOTO = "Photo"
    PHOTO_ALBUM = "PhotoAlbum"
    PLAYLIST = "Playlist"
    PLAYLISTS_FOLDER = "PlaylistsFolder"
    PROGRAM = "Program"
    RECORDING = "Recording"
    SEASON = "Season"
    SERIES = "Series"
    STUDIO = "Studio"
    TRAILER = "Trailer"
    TV_CHANNEL = "TvChannel"
    TV_PROGRAM = "TvProgram"
    USER_ROOT_FOLDER = "UserRootFolder"
    USER_VIEW = "UserView"
    VIDEO = "Video"
    YEAR = "Year"


class ImageType(StrEnum):
    PRIMARY = "Primary"
    ART = "Art"
    BACKDROP = "Backdrop"
    BANNER = "Banner"
    LOGO = "Logo"
    THUMB = "Thumb"
    DISC = "Disc"
    BOX = "Box"
    SCREENSHOT = "Screenshot"
    MENU = "Menu"
    CHAPTER = "Chapter"
    BOXREAR = "BoxRear"
    BOX_REAR = "BoxRear"
    PROFILE = "Profile"

class MediaType(StrEnum):
    UNKNOWN = "Unknown"
    VIDEO = "Video"
    AUDIO = "Audio"
    PHOTO = "Photo"
    BOOK = "Book"

class HTTPAction(StrEnum):
    GET = "GET"
    POST = "POST"
    DELETE = "DELETE"

class ItemFields(StrEnum):
    AIR_TIME = "AirTime"
    CAN_DELETE = "CanDelete"
    CAN_DOWNLOAD = "CanDownload"
    CHANNEL_INFO = "ChannelInfo"
    CHAPTERS = "Chapters"
    TRICKPLAY = "Trickplay"
    CHILD_COUNT = "ChildCount"
    CUMULATIVE_RUN_TIME_TICKS = "CumulativeRunTimeTicks"
    CUSTOM_RATING = "CustomRating"
    DATE_CREATED = "DateCreated"
    DATE_LAST_MEDIA_ADDED = "DateLastMediaAdded"
    DISPLAY_PREFERENCES_ID = "DisplayPreferencesId"
    ETAG = "Etag"
    EXTERNAL_URLS = "ExternalUrls"
    GENRES = "Genres"
    HOME_PAGE_URL = "HomePageUrl"
    ITEM_COUNTS = "ItemCounts"
    MEDIA_SOURCE_COUNT = "MediaSourceCount"
    MEDIA_SOURCES = "MediaSources"
    ORIGINAL_TITLE = "OriginalTitle"
    OVERVIEW = "Overview"
    PARENT_ID = "ParentId"
    PATH = "Path"
    PEOPLE = "People"
    PLAY_ACCESS = "PlayAccess"
    PRODUCTION_LOCATIONS = "ProductionLocations"
    PROVIDER_IDS = "ProviderIds"
    PRIMARY_ASPECT_RATIO = "PrimaryImageAspectRatio"
    RECURSIVE_ITEM_COUNT = "RecursiveItemCount"
    SETTINGS = "Settings"
    SCREENSHOT_IMAGE_TAGS = "ScreenshotImageTags"
    SERIES_PRIMARY_IMAGE = "SeriesPrimaryImage"
    SERIES_STUDIO = "SeriesStudio"
    SORT_NAME = "SortName"
    SPECIAL_EPISODE_NUMBERS = "SpecialEpisodeNumbers"
    STUDIOS = "Studios"
    TAGLINES = "Taglines"
    TAGS = "Tags"
    REMOTE_TRAILERS = "RemoteTrailers"
    MEDIA_STREAMS = "MediaStreams"
    SEASON_USER_DATA = "SeasonUserData"
    SERVICE_NAME = "ServiceName"
    THEME_SONG_IDS = "ThemeSongIds"
    THEME_VIDEO_IDS = "ThemeVideoIds"
    EXTERNAL_ETAG = "ExternalEtag"
    PRESENTATION_UNIQUE_KEY = "PresentationUniqueKey"
    INHERITED_PARENTAL_RATING_VALUE = "InheritedParentalRatingValue"
    EXTERNAL_SERIES_ID = "ExternalSeriesId"
    SERIES_PRESENTATION_UNIQUE_KEY = "SeriesPresentationUniqueKey"
    DATE_LAST_REFRESHED = "DateLastRefreshed"
    DATE_LAST_SAVED = "DateLastSaved"
    REFRESH_STATE = "RefreshState"
    CHANNEL_IMAGE = "ChannelImage"
    ENABLE_MEDIA_SOURCE_DISPLAY = "EnableMediaSourceDisplay"
    WIDTH = "Width"
    HEIGHT = "Height"
    EXTRA_IDS = "ExtraIds"
    LOCAL_TRAILER_COUNT = "LocalTrailerCount"
    IS_HD = "IsHD"
    SPECIAL_FEATURE_COUNT = "SpecialFeatureCount"
